/**
 * Generated by create-intellisense from src/v24.
 * Do not edit this file directly.
 */

export type TallyApi = {
    company: {
        /** Fetches company list from Tally. */
        fetch: (inParam: string, ...inArgs: any[]) => Promise<any>;
    };
    vouchers: {
        purchases: {
            /** Fetches purchase vouchers. */
            fetch: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
        sales: {
            /** Fetches sales vouchers. */
            fetch: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
    };
    masters: {
        unit: {
            /** Fetches all units. */
            all: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
        stockItem: {
            /** Fetches all stock items. */
            all: (inParam: string, ...inArgs: any[]) => Promise<any>;
            /** Fetches stock items with base units. */
            withBaseUnits: (inParam: string, ...inArgs: any[]) => Promise<any>;
            /** Fetches stock items with batches. */
            withBatches: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
        ledger: {
            /** Fetches all ledgers. */
            all: (inParam: string, ...inArgs: any[]) => Promise<any>;
            /** Fetches ledgers with GSTIN details. */
            withDetails: (inParam: string, ...inArgs: any[]) => Promise<any>;
            /** Fetches ledgers with full GST registration details. */
            withGstDetails: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
        stockGroup: {
            /** Fetches all stock groups. */
            all: (inParam: string, ...inArgs: any[]) => Promise<any>;
            /** Fetches stock groups with parent hierarchies. */
            withParent: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
        godown: {
            /** Fetches all godowns. */
            all: (inParam: string, ...inArgs: any[]) => Promise<any>;
            /** Fetches godowns with parent hierarchies. */
            withParent: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
    };
    reports: {
        stockSummary: {
            /** Fetches the Stock Summary report from Tally. */
            fetch: (inParam: string, ...inArgs: any[]) => Promise<any>;
        };
    };
};

declare const tally: TallyApi;

export default tally;
